          # docker-compose.prod.yml (overrides)
          version: '3.8'

          tervices:
            klario-app:
              build: false
              image: yourregistry/klario:${TAG}
              env_file:
                - .env

            proxy:
              volumes:
                - ./Caddyfile:/etc/caddy/Caddyfile:ro
                - caddy_data:/data
                - caddy_config:/config

            db-backup:
              image: postgres:15-alpine
              container_name: klario-backup
              restart: unless-stopped
              environment:
                POSTGRES_DB: klario
                POSTGRES_USER: klario_user
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                BACKUP_RETENTION_DAYS: 7
              volumes:
                - postgres_backups:/backups
                - ./scripts/backup.sh:/usr/local/bin/backup.sh:ro
              networks:
                - klario-network
              depends_on:
                - postgres
              command: |
                sh -c "while true; do /usr/local/bin/backup.sh && sleep 86400; done"

          volumes:
            postgres_backups:
              driver: local